spring.datasource.url=jdbc:mysql://localhost:3306/petclinic?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=P@ssw0rd
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# If Petclinic uses Spring SQL init:
#spring.sql.init.schema-locations=classpath*:db/mysql/schema.sql
spring.sql.init.data-locations=classpath*:db/mysql/data.sql
spring.sql.init.mode=always


spring.flyway.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
